### ISSUE TITLE
addTicket does not Add Ticket

### ISSUE THREAD

**Issue by naterush** [blockchain-mobility-ecosystem/Commuterz#1]
Within addTicket function, though totalAmount is updated -- seemingly accepting the ticket -- it is not added to the tickets array.

I believe this could be fixed by adding the line **tickets.push(ticket);** at the end of the function. 

Alternatively, I believe it would be cheaper (gas-wise) to simply delete lines 31 - 35, and instead, add the following code:
`        tickets.push(Ticket({
            user: user,
            amount: amount,
            sumTicketsAmounts: totalAmount}));`

**Comment by yaronvel** [comment]
Thanks.
Fixed at commit [14aaa16b4b38386a0476ad37e641b921da67a3fa](https://github.com/blockchain-mobility-ecosystem/Commuterz/commit/14aaa16b4b38386a0476ad37e641b921da67a3fa)

Deleting lines 31-35 will not save gas IMO, as the compiler will have to add such EVM code anyway.

**Comment by naterush** [comment]
Looks good! And no problem. 

Though the drop in gas cost is negligble, from my tests this change would reduce the gas cost of running the function from 101306 to 101181, which is a measly savings of 125 gas. 

This is likely as the compiler is better able to optimize the shorter code. However, its so negligble it's probably not worth it.

**Comment by yaronvel** [comment]
Well if you tried it and have the code, a PR would be appreciated.
Otherwise, 125 gas is indeed small, but also makes you wonder if in the next compiler version it would not be the other way around (e.g., 125 gas more). Hard to predict how compiler optimizations would work.

**Comment by yaronvel** [comment]
Fixed in commit bac9bfcd8b4c7ba76d38c1d167199a42933a2562
